ci:
  # skip any check that needs internet access
  skip: [check-jsonschema, prettier, integrity]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: forbid-new-submodules
      - id: check-case-conflict
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: debug-statements

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.14.2
    hooks:
      - id: check-jsonschema
        name: 'Check GitHub Workflows'
        files: ^\.github/workflows/
        types: [yaml]
        args: ['--schemafile', 'https://json.schemastore.org/github-workflow']

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: 'npm run prettier:files'
        language: node
        types_or: [json, markdown, ts, tsx, javascript, jsx, css]
      - id: integrity
        name: integrity
        entry: 'npm run integrity --force'
        language: node
        stages: [push]
